version: "3"
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "Investimento"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:


