version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - ${HOME}/develop/postgres-data/:/var/lib/postgresql/data
    networks:
      - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "julioafonsso@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
