spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: jdbc:postgresql://localhost:15432/Investimento
        username: postgres
        password: postgres
    batch:
#      job:
#        enabled: false
      jdbc:
        initialize-schema: ALWAYS
