export const CATEGORY = {
    BRASIL: 1,
    USA: 12
}

export const SETOR = {
    BEN_INDUSTRIAIS: 1,
    CONSUMO_CICLICO: 2,
    CONSUMO_NAO_CICLICO: 3,
    FINANCEIROS_OUTROS: 4,
    MATERIAIS_BASICO: 5,
    PETROLEO_GAS: 6,
    SAUDE: 7,
    TECNLOGIA_INFORMACAO: 8,
    COMUNICACAO: 9,
    UTILIDADE_PUBLICA: 10
}